name: build-test-deploy
on:
  push:
    branches:
      - main  # Adjust this if you use a different branch for deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use the latest supported Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Vite will build and output to the 'dist' folder

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust if your Vue.js project doesn't include tests

  deploy:
    needs: test  # Ensure deploy only runs after tests pass
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build for deployment
        run: npm run build  # Ensure this matches your Vue.js build script

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"  # Matches Vite's default output directory

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
