name: build-test-deploy
on:
  push:
    branches:
      - main  # Adjust for your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Updated to use the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # This will output to the 'dist' directory by default for Vite

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Ensure you have a test script or remove this step if not applicable

  deploy:
    #needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build for deployment
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist"  # Ensure this matches Vite's output directory

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
